### ISSUE TITLE
Only renders when there is a single diagram

### ISSUE THREAD

**Issue by sahlouls** [Redisrupt/mermaid-diagrams#9] opened 2019-02-25 20:27 UTC
Hi,
If a github page for example, contains more than a diagram, then, none is displayed.
How to enable multiple diagrams rendering ?
Thanks

**Comment by royriojas** [comment] 2019-02-25 20:50
hi @sahlouls, this is a very nasty bug. It is supposed to render for multiple, maybe github have changed the markup it generates for code blocks? because it is supposed to work for any number of them

**Comment by sahlouls** [comment] 2019-02-25 20:54
How can I help ? really annoying bug indeed.

**Comment by royriojas** [comment] 2019-02-25 21:08
hi @sahlouls a quick and dirty fix is to wrap your graph in a div to make it not have the same parent. The bug is in this file: https://github.com/Redisrupt/mermaid-diagrams/blob/master/extension/content.js#L6

The issue is that is checking for a graphic on the same parentElement. We should probably wrap the block in a div to avoid this issue during the graph render, but manually wrapping the element will work as a workaround. Check the readme page: 

**Example 1**
<div>

```mermaid
sequenceDiagram
  A->> B: Query
  B->> C: Forward query
  Note right of C: Thinking...
  C->> B: Response
  B->> A: Forward response
```

</div>

**Example 2**

<div>

```mermaid
sequenceDiagram
  A->> B: Query B
  B->> C: Forward query B
  Note right of C: Thinking of B...
  C->> B: Response of B
  B->> A: Forward response of B
```

</div>

**Comment by royriojas** [comment] 2019-02-25 21:09
@sahlouls PRs welcome though, as we just need to wrap the graph during the graph render phase, it might be a simpler fix, if you're interested.

Kind regards

**Comment by sahlouls** [comment] 2019-02-25 22:36
Thanks @royriojas for the workaround.
- First maybe add some documentation about it this little bug (as of today).
- Until this case will be properly handled with a surrounding `div` or another solution
Thanks

**Comment by filipverlee** [comment] 2019-07-25 12:03
First of all great tool! But is there anyway you could add Azure Devops also. Would be great in combination with the AzureDevops Wiki. Thnx in advance!

**Comment by howard0su** [comment] 2019-12-26 01:24
I fixed this in #11 as well as Azure Devops cannot use this workaround.

**Comment by royriojas** [comment] 2019-12-26 20:20
Very nice @howard0su will review and merge it

**Comment by howard0su** [comment] 2019-12-31 11:26
Thank you. Look forward the merge.

**Comment by howard0su** [comment] 2020-01-07 12:35
any update?

**Comment by royriojas** [comment] 2020-01-08 17:49
hi @howard0su, 

I'm been busy lately, will try to give it a try today or tomorrow. Sorry for the big delay and thanks for you patient

**Comment by royriojas** [comment] 2020-06-21 23:39
Sorry for the so long to update this, but this is already merged to master. Will test it and push a new version to the chrome store.

**Closed as completed by royriojas** 2020-06-21 23:39 UTC
